// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qhphxxvfqaizzhneaawb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFocGh4eHZmcWFpenpobmVhYXdiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzg0MjcwNDMsImV4cCI6MjA1NDAwMzA0M30.8JbyPWXJEQPD7P-w4CwN7Ju8nmGYgr8CkCWiGCDeqpc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);